In [10]:
import numpy as np
from sklearn.neighbors import KDTree
import time

In [13]:
rng = np.random.RandomState(0)
X = rng.random_sample((1000000, 100))  # 10 points in 3 dimensions

In [14]:
start_time = time.time()
tree = KDTree(X, leaf_size=2)  
end_time = time.time()
print('Time: {}s'.format(end_time-start_time))

Time: 161.23804020881653s


In [7]:
dist, ind = tree.query(X[:10], k=3)                
print(ind)  # indices of 3 closest neighbors

print(dist)  # distances to 3 closest neighbors

[[   0 4570 8894]
 [   1 1203 3928]
 [   2 2432 2596]
 [   3 5699 3816]
 [   4 8818 8563]
 [   5 6667 5077]
 [   6 7909 8497]
 [   7 4690 2661]
 [   8 4313 6239]
 [   9 1555 3940]]
[[0.         3.21795666 3.22633538]
 [0.         3.14403209 3.18422455]
 [0.         3.31643304 3.31888397]
 [0.         3.12992588 3.21080126]
 [0.         3.17995234 3.27369502]
 [0.         3.32398653 3.33699009]
 [0.         3.12683558 3.13653705]
 [0.         3.34167285 3.34930331]
 [0.         3.15659087 3.17351352]
 [0.         3.31107933 3.33792927]]
